# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


sharedCorePod = 'shared_core'
sharedCorePath = '../shared_core'

target 'iosKlibError' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod sharedCorePod, :path => sharedCorePath
  # Pods for iosKlibError

  target 'iosKlibErrorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosKlibErrorUITests' do
    # Pods for testing
  end

end


post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
